name: indigo24
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  web_socket_channel: ^1.1.0
  websocket_manager: ^0.2.2
  sembast: ^2.4.4+1
  path_provider: ^1.6.10
  connectivity: ^0.4.8+6
  contacts_service: ^0.4.6
  shimmer: ^1.1.0
  flutter_slidable: ^0.5.4
  polygon_clipper: ^1.0.2
  dio: ^3.0.9
  flutter_progress_button: ^1.0.0
  http: ^0.12.1
  shared_preferences: any
  permission_handler: ^5.0.0+hotfix.6
  video_player: ^0.10.11+1
  photo_view: ^0.9.2
  image_picker: ^0.6.7+1
  platform_action_sheet: ^0.0.3
  cached_network_image: ^2.2.0+1
  chewie: ^0.9.10
  fab_circular_menu: ^1.0.0
  flutter_emoji: ^2.2.1+1
  pull_to_refresh: ^1.5.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/cover.png
    - assets/images/avatar.png
    - assets/images/tape.png
    - assets/images/chat.png
    - assets/images/wallet.png
    - assets/images/background_login.png
    - assets/loading.gif
    - assets/images/profile.png
    - assets/images/payments.png
    - assets/images/transfers.png
    - assets/images/background_chat.png
    - assets/images/walletBackground.png
    - assets/images/background_little.png

  fonts:
     - family: Spectral
       fonts:
         - asset: assets/fonts/Spectral-Regular.ttf
           weight: 400
         - asset: assets/fonts/Spectral-Medium.ttf
           weight: 500
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Light.ttf
           weight: 200
         - asset: assets/fonts/Roboto-Bold.ttf
           weight: 700

