name: indigo24
description: A new Flutter project.

publish_to: 'none' 

version: 0.2.71+31

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  scrollable_positioned_list: ^0.1.6
  cupertino_icons: ^0.1.3
  native_pdf_view: ^3.6.2
  percent_indicator: ^2.1.5
  file: any
  flutter_swiper: ^1.1.6
  vibration: ^1.4.0
  overlay_support: ^1.0.4
  record_mp3: ^2.0.0
  web_socket_channel: ^1.1.0
  sembast: ^2.4.4+1
  path_provider: ^1.6.10
  provider: any
  connectivity: ^0.4.8+6
  contacts_service: ^0.4.6
  shimmer: ^1.1.0
  flutter_slidable: ^0.5.4
  polygon_clipper: ^1.0.2
  dio: ^3.0.9
  flutter_progress_button: ^1.0.0
  shared_preferences: any
  permission_handler: ^5.0.0+hotfix.6
  video_player: ^0.10.11+1
  photo_view: ^0.9.2
  image_picker: ^0.6.7+1
  platform_action_sheet: ^0.0.3
  cached_network_image: ^2.2.0+1
  chewie: ^0.9.10
  fab_circular_menu: ^1.0.0
  flutter_emoji: ^2.2.1+1
  pull_to_refresh: ^1.6.3
  audioplayers: ^0.15.1
  url_launcher: ^5.4.10
  file_picker: ^1.11.0+3
  firebase_messaging: ^6.0.16
  flutter_webview_plugin: ^0.3.11
  mask_text_input_formatter: ^1.0.7
  datetime_picker_formfield: ^1.0.0
  flutter_image_compress: ^0.6.8
  heic_to_jpg: ^0.1.1
  marquee: ^1.5.2
  app_settings: ^4.0.1+1
  gallery_saver: ^2.0.1
  metadata_fetch: ^0.3.2
  flutter_interactive_keyboard: ^0.1.3
  share: ^0.6.5+4
  receive_sharing_intent: ^1.4.0+2
  flick_video_player: ^0.1.1
  flutter_widgets: ^0.1.12
  package_info: ^0.4.1
  flutter_cache_manager: any
  http: ^0.12.2
  hive: ^1.4.4
  hive_flutter: ^0.3.0+2
  flutter_audio_recorder: ^0.5.5
  screenshot: ^0.2.0
  flutter_bloc: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.10.1
  json_serializable: ^3.4.1
  
flutter:

  uses-material-design: true

  assets:
    - assets/sound/
    - assets/images/
    - assets/

  # fonts:
  #    - family: Spectral
  #      fonts:
  #        - asset: assets/fonts/Spectral-Regular.ttf
  #          weight: 400
  #        - asset: assets/fonts/Spectral-Medium.ttf
  #          weight: 500
  #    - family: Roboto
  #      fonts:
  #        - asset: assets/fonts/Roboto-Light.ttf
  #          weight: 200
  #        - asset: assets/fonts/Roboto-Bold.ttf
  #          weight: 700
