name: indigo24
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  file: any
  overlay_support: ^1.0.4
  record_mp3: ^2.0.0
  web_socket_channel: ^1.1.0
  websocket_manager: ^0.2.2
  sembast: ^2.4.4+1
  path_provider: ^1.6.10
  connectivity: ^0.4.8+6
  contacts_service: ^0.4.6
  shimmer: ^1.1.0
  flutter_slidable: ^0.5.4
  polygon_clipper: ^1.0.2
  dio: ^3.0.9
  flutter_progress_button: ^1.0.0
  shared_preferences: any
  permission_handler: ^5.0.0+hotfix.6
  video_player: ^0.10.11+1
  photo_view: ^0.9.2
  image_picker: ^0.6.7+1
  platform_action_sheet: ^0.0.3
  cached_network_image: ^2.2.0+1
  chewie: ^0.9.10
  fab_circular_menu: ^1.0.0
  flutter_emoji: ^2.2.1+1
  pull_to_refresh: ^1.5.8
  audioplayers: ^0.15.1
  url_launcher: ^5.4.10
  file_picker: ^1.11.0+3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/empty.gif
    - assets/chat_animation.gif
    - assets/sound/messageIn.mp3
    - assets/sound/msg_out.mp3
    - assets/sound/message_in.mp3
    - assets/images/send.png
    - assets/images/cover.png
    - assets/images/avatar.png
    - assets/images/tape.png
    - assets/images/chat.png
    - assets/images/wallet.png
    - assets/images/background_login.png
    - assets/loading.gif
    - assets/images/profile.png
    - assets/images/payments.png
    - assets/images/transfers.png
    - assets/images/background_chat.png
    - assets/images/walletBackground.png
    - assets/images/background_little.png
    - assets/images/eyeOpen.png
    - assets/images/eyeClose.png
    - assets/images/tapeComment.png
    - assets/images/tapeLiked.png
    - assets/images/tapeUnliked.png
    - assets/images/back.png
    - assets/images/backWhite.png
    - assets/images/history.png
    - assets/images/money.png
    - assets/images/camera.png
    - assets/images/gallery.png
    - assets/images/files.png

  fonts:
     - family: Spectral
       fonts:
         - asset: assets/fonts/Spectral-Regular.ttf
           weight: 400
         - asset: assets/fonts/Spectral-Medium.ttf
           weight: 500
     - family: Roboto
       fonts:
         - asset: assets/fonts/Roboto-Light.ttf
           weight: 200
         - asset: assets/fonts/Roboto-Bold.ttf
           weight: 700
