import '../language_interface.dart';

class EN implements LanguageInterface {
  String code = 'en';

  String signUp = 'Registration';
  String title = 'Title';
  String signIn = 'Sign In';
  String phoneNumber = 'Phone number';
  String password = 'Password';
  String forgotPassword = 'Forgot password';
  String next = 'Next';
  String currentLanguage = 'English';
  String email = 'Email';
  String exit = 'Exit';
  String support = 'SUPPORT SERVICE';
  String chats = 'Chats';
  String chat = 'Chat';
  String profile = 'Profile';
  String tape = 'Tapes';
  String wallet = 'Wallet';
  String comments = 'Comments';
  String withdraw = 'Withdraw';
  String refill = 'Refill';
  String payments = 'Payments';
  String transfers = 'Transfers';
  String balanceInBlock = 'Balance in processing';
  String balance = 'Balance';
  String account = 'Account';
  String walletBalance = 'Wallet balance';
  String amount = 'Amount';
  String minAmount = 'Minimum amount';
  String minCommission = 'Minimum commission';
  String maxAmount = 'Maximum amount';
  String commission = 'Commission';
  String toIndigo24Client = 'To Indigo24 Client';
  String transfer = 'Transfer';
  String pay = 'Pay';
  String enterMessage = 'Enter your message';
  String members = 'Members';
  String creator = 'Creator';
  String member = 'Member';
  String contacts = 'Contacts';
  String search = 'Search';
  String createGroup = 'Create group';
  String chatName = 'Chat name';
  String newTape = 'New tape';
  String enterPin = 'Enter passcode';
  String createPin = 'Set passcode';
  String incorrectPin = 'Incorrect PIN';
  String chatNotifications = 'Chat notifications';
  String error = 'Error';
  String notifications = 'Notifications';
  String hideNotifications = 'Hide notifications';
  String messagePreview = 'Message preview';
  String sound = 'Sound';
  String language = 'Language';
  String settings = 'Settings';
  String enterPhone = 'Enter phone';
  String enterSmsCode = 'Enter SMS code';
  String enterPassword = 'Enter password';
  String repeatPin = 'Repeat pin';
  String attention = 'Alert';
  String admin = 'Admin';
  String lastSeen = 'Last seen';
  String video = 'Video';
  String selectOption = 'Select option';
  String gallery = 'Gallery';
  String wantToExit = 'Are you sure want to logout';
  String uploaded = 'Uploaded';
  String somethingWentWrong = 'Somethin went wrong';
  String save = 'Save';
  String share = 'Share';
  String photo = 'Photo';
  String sessionIsOver = 'Your account was signed in with a different device';
  String cancel = 'Cancel';
  String allowContacts = 'Allow contacts';
  String openSettings = 'Open settings';
  String document = 'Document';
  String textMessage = 'Text message';
  String voiceMessage = 'Voice message';
  String location = 'Location';
  String reply = 'Reply';
  String money = 'Money';
  String link = 'Link';
  String forwardedMessage = 'Forwarded message';
  String message = 'Message';
  String systemMessage = 'System message';
  String back = 'Back';
  String camera = 'Camera';
  String watch = 'Watch';
  String no = 'No';
  String yes = 'Yes';
  String fillAllFields = 'Fill all fields';
  String description = 'Description';
  String goToChat = 'Go to chat';
  String userNotInSystem = 'This user is not in the system';
  String file = 'File';
  String addToGroup = 'Add to group';
  String clickToStart = 'Tap to start chat';
  String setAdmin = 'Set admin rights';
  String makeMember = 'Make member';
  String exitGroup = 'Exit group';
  String sureExitGroup = 'Are sure exit group';
  String delete = 'Delete';
  String noChatName = 'No chat name';
  String minMembersCount = 'Minimum count of members 3';
  String files = 'Files';
  String edit = 'Edit';
  String editedMessage = 'Edited';
  String surname = 'Surname';
  String passwordNotMatch = 'Passwords must be identical';
  String weSentToEmail =
      'We have sent an SMS key to your number, which will arrive within 10 seconds';
  String keyFromSms = 'SMS code';
  String country = 'Country';
  String status = 'Status';
  String selectFile = 'Select file';
  String userNotFound = 'User not found';
  String history = 'History';
  String youSended = 'You have sended';
  String receiver = 'Receiver';
  String online = 'online';
  String enterValidAccount = 'Enter the correct account number';
  String enterBelowMax = 'Enter the amount below the maximum mark';
  String enterAboveMin = 'Enter the amount above the minimum mark';
  String appVersion = 'App version';
  String httpError = 'Error while loading data';
  String historyBalance = 'Balance history';
  String emptyContacts = 'Contacts is empty';
  String empty = 'Empty';
  String noChats = 'No chats';
  String terms = "Terms of use";
  String hide = 'Hide';
  String block = 'Block';
  String repeat = 'Repeat';
  String calculate = 'Calculate';
  String service = 'Service';
  String toPay = 'To pay';
  String conversion = 'Conversion';
  String mute = 'Mute';
  String unmute = 'Unmute';
  String open = 'Open';
  String thankYou = 'Thank you';
  String returning = 'Returning';
  String withLove = 'With love';
  String methods = 'Methods';
  String identification = 'Identification';
  String identified = 'Identified';
  String notIdentified = 'Not identified';
  String simpleIdentified = 'Simplified identified';
  String decor = 'Decor';
  String decorForChat = 'Decor for chat';
  String hello = 'Hello';
  String hi = 'Hi';
  String ago = 'Ago';
  String days = 'Days';
  String privacyPolicy = 'Privacy policy';
  String day = 'Day';
  String success = 'Success';
  String selectChat = 'Select chat';
  String report = 'Report';
  String forward = 'Forward';
  String forwardFrom = 'Forward from';
  String filter = ' Filter';
  String showOperations = 'Show operations ';
  String accept = 'Apply ';
  String monday = ' Monday';
  String tuesday = 'Tuesday';
  String wednesday = ' Wednesday';
  String thursday = 'Thursday';
  String friday = ' Friday ';
  String saturday = '  Saturday';
  String sunday = 'Sunday';
  String today = 'Today ';
  String city = 'City';
  String name = 'Name';
  String example = 'Example';
  String more = 'More';
  String less = 'Less';
  String newPayment = 'New payment';
  String pending = 'Pending';
  String hours = 'Hours';
  String minutes = 'Minutes';
  String likes = 'Likes';
  String withdrawTerm =
      "I confirm that the specified bank account / bank card belongs to me and (or) I have a legal basis for his / her use (disposal of funds on the account)";
  String payFrom = 'Paid from';
  String date = 'Date';
  String destination = 'Payment address';
  String iAgree = "I accept the user agreement";
  String paymentsHistory = 'Payments history';
  String transfersHistory = 'Transfers history';
  String reveiverPhone = 'Receiver phone';
  String transferAmount = 'Transfer amount';
  String infoAboutConfidentional = 'Privacy Information';
  String confidentionalAgreement =
      "The client undertakes to independently take all necessary measures to preserve confidentiality, prevent unauthorized use and protect his authentication data from unauthorized access by third parties. The client undertakes not to disclose his authentication data: login, password, PIN to third parties, ie. not to transfer his authentication data and confirms that he is independently responsible for the safety of confidential information and for the dissemination of data, as well as for possible financial losses as a result of the transfer of authentication data ";
  String simpleIdentification = "Simplified identification";
  String fullIdentification = "Full identification";
  String afterFullIdentification =
      "Complete identification, when you are already simplistically identified";
  String currentlyNotWorking = "Currently not working";
  String infoAboutIdentification = "Customer identification information";

  String instruction = 'Инструкция';
  String identificationNote =
      'Примечание: Стоимость упрощенной идентификации клиента (УИК) - 400 тенге. С вашего баланса спишется сумма 400 тенге за прохождение упрощенной идентификации.';
  String step = 'Шаг ';
  String identificationStepOne =
      'Для упрощенной идентификации нажимаем на кнопку (смотреть ниже)';
  String identificationStepTwo =
      'Вас переносит в браузер, где просят ввести данные (смотреть ниже)';
  String identificationStepThree = 'Введите свой ИИН';
  String identificationStepFour =
      'Нажимаете на “Выбрать файл” для загрузки фотографии лица';
  String identificationStepFive =
      'Нажимаете на “Выбрать файл” для загрузки видео лица';
  String identificationStepSix =
      'Нажимаете на “Выбрать файл” для загрузки фотографии удостоверения личности спереди';
  String identificationStepSeven =
      'Нажимаете на “Выбрать файл” для загрузки фотографии удостоверения личности сзади';
  String identificationStepEight =
      'После ввода и отправки всех данных, статус вашей заявки поступит на почту, указанную в приложении INDIGO24. Также вы можете проверить статус идентификации в профиле приложения INDIGO24';
  String infoAboutSimpleIdentification =
      'Инструкция по упрощенной идентификации';
  String forUserInfoHeader =
      'For the information of owners of electronic money "Indigo24"';
  String forUserInfoBody =
      '"Indigo24" LLP, which is the operator of the "Indigo24" electronic money system, notifies you that in connection with the Resolution adopted by the authorized body to revoke the license of the "Indigo24" System Issuer - "AsiaCredit Bank" JSC (AsiaCredit Bank) for banking and other operations and activities in the securities market, the operator is obliged to stop operations using electronic money issued by this issuer in accordance with the requirements of the current legislation. In this connection, all operations in the System "Indigo24" will be suspended until the connection of the issuing bank JSC SB "Alfa-Bank" to the System. Further actions for refund will be announced additionally on our official website https://indigo24.com. For all questions of interest, you can contact the temporary administration of AsiaCredit Bank JSC by phones: +7 (727) 330 88 11, 355 05 35.';
  String forUserInfoFooter = 'Best regards, Management of "Indigo24" LLP';
  String forUserInfoDear = "Dear Users!";
  String alfaBank = 'Alfa-bank';

  String asiaCreditBank = 'AO "AsiaCredit Bank (AsiaCredit Bank)" ';

  String eMoneyBalance = 'Electronic money balance';
}
