abstract class DefaultLanguage {
  final String code = 'ru';

  String signUp = 'Регистрация';
  String signIn = 'Вход';
  String title = 'Название';
  String phoneNumber = 'Номер телефона';
  String password = 'Пароль';
  String forgotPassword = 'Забыли пароль?'; // НЕТ ПЕРЕВОДА
  String next = 'Далее';
  String currentLanguage = 'Русский';
  String email = 'Почта';
  String exit = 'Выйти';
  String support = 'СЛУЖБА ПОДДЕРЖКИ';
  String chats = 'Чаты';
  String chat = 'Чат';
  String profile = 'Профиль';
  String tape = 'Лента';
  String wallet = 'Кошелек';
  String comments = 'Комментарии';
  String withdraw = 'Вывести';
  String refill = 'Пополнить';
  String payments = 'Платежи';
  String transfers = 'Переводы';
  String balanceInBlock = 'Баланс в обработке';
  String balance = 'Баланс';
  String account = 'Аккаунт';
  String walletBalance = 'Баланс кошелька';
  String amount = 'Сумма';
  String pay = 'Оплатить';
  String minAmount = 'Минимальная сумма';
  String minCommission = 'Минимальная комиссия';
  String maxAmount = 'Максимальная сумма';
  String commission = 'Комиссия';
  String toIndigo24Client = 'Клиенту Indigo24';
  String transfer = 'Перевести';
  String enterMessage = 'Введите ваше сообщение';
  String members = 'Участников';
  String creator = 'Создатель';
  String member = 'Участник';
  String contacts = 'Контакты'; // НЕТ ПЕРЕВОДА
  String search = 'Поиск';
  String createGroup = 'Создать группу';
  String chatName = 'Название чата';
  String newTape = 'Новая запись';
  String enterPin = 'Введите PIN';
  String createPin = 'Установите PIN';
  String incorrectPin = 'Неправильный PIN';
  String chatNotifications = 'Уведомления от чатов';
  String notifications = 'Уведомления';
  String hideNotifications = 'Скрывать уведомления'; // НЕТ ПЕРЕВОДА
  String error = 'Ошибка';
  String messagePreview = 'Показывать текст';
  String sound = 'Звук';
  String language = 'Язык';
  String settings = 'Настройки';
  String enterPhone = 'Введите номер телефона';
  String enterSmsCode = 'Введите SMS код';
  String enterPassword = 'Введите пароль';
  String repeatPin = 'Повторите PIN';
  String attention = 'Внимание';
  String admin = 'Администратор';
  String lastSeen = 'Был в сети';
  String video = 'Видео';
  String selectOption = 'Выберите опцию';
  String gallery = 'Галерея';
  String wantToExit = 'Уверены, что хотите выйти';
  String uploaded = 'Загружено';
  String somethingWentWrong = 'Что-то пошло не так';
  String save = 'Сохранить';
  String share = 'Поделиться';
  String photo = 'Фото';
  String sessionIsOver = 'На ваш аккаунт вошли через другое устройство';
  String cancel = 'Cancel';
  String allowContacts = 'Разрешить контакты';
  String openSettings = 'Открыть настройки';
  String document = 'Документ';
  String textMessage = 'Текстовое сообщение';
  String voiceMessage = 'Голосовое сообщение';
  String location = 'Местоположение';
  String reply = 'Ответить';
  String money = 'Деньги';
  String link = 'Ссылка';
  String forwardedMessage = 'Переотправленное сообщение';
  String message = 'Сообщение'; // НЕТ ПЕРЕВОДА
  String systemMessage = 'Системное сообщение';
  String back = 'Назад';
  String camera = 'Камера'; // НЕТ ПЕРЕВОДА
  String watch = 'Посмотреть'; // НЕТ ПЕРЕВОДА
  String no = 'Нет';
  String yes = 'Да';
  String fillAllFields = 'Заполните все поля';
  String description = 'Описание';
  String goToChat = 'Перейти в чат';
  String userNotInSystem = 'This user is not in the system';
  String file = 'Файл'; // НЕТ ПЕРЕВОДА
  String addToGroup = 'Добавить в группу';
  String clickToStart = 'Нажмите, чтобы начать чат';
  String setAdmin = 'Назначить администратором';
  String makeMember = 'Сделать участником';
  String exitGroup = 'Выйти из группы';
  String sureExitGroup = 'Уверены, что хотите выйти из группы?';
  String delete = 'Удалить';
  String noChatName = 'Нет названия чата';
  String minMembersCount = 'Минимальное количество участников: 3';
  String files = 'Файлы';
  String edit = 'Редактировать';
  String editedMessage = 'Ред';
  String surname = 'Фамилия';
  String passwordNotMatch = 'Пароли не совпадают';
  String weSentToEmail =
      'Мы отправили на ваш номер SMS ключ, который поступит в течение 10 секунд';
  String keyFromSms = 'SMS код';
  String country = 'Страна';
  String status = 'Статус';
  String selectFile = 'Выберите файл';
  String userNotFound = 'Пользователь не найден';
  String history = 'История';
  String youSended = 'Вы отправили';
  String receiver = 'Получатель';
  String online = 'онлайн';
  String enterValidAccount = 'Введите корректный номер аккаунта';
  String enterBelowMax = 'Введите сумму ниже максимальной отметки';
  String enterAboveMin = 'Введите сумму выше минимальной отметки';
  String appVersion = 'Версия приложения'; // НЕТ ПЕРЕВОДА
  String httpError = 'Ошибка при загрузке данных'; // НЕТ ПЕРЕВОДА
  String historyBalance = 'История баланса';
  String emptyContacts = 'Контакты пусты'; // НЕТ ПЕРЕВОДА
  String empty = 'Пусто';
  String noChats = 'Нет чатов'; // НЕТ ПЕРЕВОДА
  String terms = "Пользовательское соглашение"; // НЕТ ПЕРЕВОДА
  String hide = 'Скрыть';
  String block = 'Заблокировать'; // НЕТ ПЕРЕВОДА
  String repeat = 'Повторить';
  String calculate = 'Посчитать'; // НЕТ ПЕРЕВОДА
  String service = 'Сервис';
  String toPay = 'К оплате'; // НЕТ ПЕРЕВОДА
  String conversion = 'Конвертация'; // НЕТ ПЕРЕВОДА
  String open = 'Открыть'; // НЕТ ПЕРЕВОДА
  String thankYou = 'Спасибо'; // НЕТ ПЕРЕВОДА
  String returning = 'Возвращаю'; // НЕТ ПЕРЕВОДА
  String withLove = 'С любовью'; // НЕТ ПЕРЕВОДА
  String mute = 'Выключить звук'; // НЕТ ПЕРЕВОДА
  String unmute = 'Включить звук'; // НЕТ ПЕРЕВОДА
  String methods = 'Методы'; // НЕТ ПЕРЕВОДА
  String identification = 'Идентификация'; // НЕТ ПЕРЕВОДА
  String identified = 'Идентифицирован'; // НЕТ ПЕРЕВОДА
  String notIdentified = 'Не идентифицирован'; // НЕТ ПЕРЕВОДА
  String decor = 'Оформление'; // НЕТ ПЕРЕВОДА
  String decorForChat = 'Оформление чата'; // НЕТ ПЕРЕВОДА
  String hello = 'Здравствуй'; // НЕТ ПЕРЕВОДА
  String hi = 'Привет'; // НЕТ ПЕРЕВОДА
  String ago = 'Назад'; // НЕТ ПЕРЕВОДА
  String days = 'Дней'; // НЕТ ПЕРЕВОДА
  String privacyPolicy = 'Политика безопасности'; // НЕТ ПЕРЕВОДА
  String day = 'День'; // НЕТ ПЕРЕВОДА
  String success = 'Успешно';
  String selectChat = 'Выберите чат'; // НЕТ ПЕРЕВОДА
  String report = 'Жалоба'; // НЕТ ПЕРЕВОДА
  String forward = 'Переслать'; // НЕТ ПЕРЕВОДА
  String forwardFrom = 'Переслано от'; // НЕТ ПЕРЕВОДА
  String filter = 'Фильтр';
  String showOperations = 'Показать операции';
  String accept = 'Применить'; // НЕТ ПЕРЕВОДА
  String monday = 'Понедельник'; // НЕТ ПЕРЕВОДА
  String tuesday = 'Вторник'; // НЕТ ПЕРЕВОДА
  String wednesday = 'Среда'; // НЕТ ПЕРЕВОДА
  String thursday = 'Четверг'; // НЕТ ПЕРЕВОДА
  String friday = 'Пятница'; // НЕТ ПЕРЕВОДА
  String saturday = 'Суббота'; // НЕТ ПЕРЕВОДА
  String sunday = 'Воскресенье'; // НЕТ ПЕРЕВОДА
  String today = 'Сегодня'; // НЕТ ПЕРЕВОДА
  String city = 'Город'; // НЕТ ПЕРЕВОДА
  String name = 'Имя';
  String example = 'Пример';
  String more = 'Еще'; // НЕТ ПЕРЕВОДА
  String less = 'Меньше'; // НЕТ ПЕРЕВОДА
  String newPayment = 'Новый платеж'; // НЕТ ПЕРЕВОДА
  String pending = 'В обработке'; // НЕТ ПЕРЕВОДА
  String hours = 'Часа'; // НЕТ ПЕРЕВОДА
  String minutes = 'Минут'; // НЕТ ПЕРЕВОДА
  String likes = 'Лайки'; // НЕТ ПЕРЕВОДА
  String withdrawTerm =
      "Подтверждаю, что указанный банковский счет/банковская карточка принадлежит мне и(или) я имею законное основание его/ее использования (распоряжения средствами, находящихся на счете)"; // НЕТ ПЕРЕВОДА
  String date = 'Дата'; // НЕТ ПЕРЕВОДА
  String payFrom = 'Оплачено с этого аккаунта'; // НЕТ ПЕРЕВОДА
  String destination = 'Адрес платежа'; // НЕТ ПЕРЕВОДА

  String iAgree = "Принимаю пользовательское соглашение"; // НЕТ ПЕРЕВОДА
  String paymentsHistory = 'История платежей'; // НЕТ ПЕРЕВОДА
  String transfersHistory = 'История Переводов'; // НЕТ ПЕРЕВОДА

  String reveiverPhone = 'Телефон получателя'; // НЕТ ПЕРЕВОДА

  String transferAmount = 'Сумма перевода'; // НЕТ ПЕРЕВОДА

  String infoAboutConfidentional = 'Информация о конфиденциальности';

  String confidentionalAgreement =
      "Клиент обязуется самостоятельно принимать все необходимые меры по сохранению конфиденциальности, предотвращению несанкционированного использования и защите своих аутентификационных данных от несанкционированного доступа со стороны третьих лиц. Клиент обязуется не сообщать свои аутентификационные данные: логин, пароль, PIN-код третьим лицам, т.е. не передавать свои аутентификационные данные и подтверждает, что самостоятельно несет ответственность за сохранность конфиденциальной информации и за распространение данных, а также за возможные финансовые убытки в результате передачи аутентификационых данных";
}
